WU.time.zones <- function(as.df = FALSE, zones = NULL) {
      TZs <- c("COLM" = "America/New_York",
               "CHAR" = "America/New_York",
               "WEBG" = "America/Chicago",
               "SPCT" = "America/New_York",
               "ORLN" = "America/New_York",
               "LTRK" = "America/Chicago",
               "MYRT" = "America/New_York",
               "HILL" = "America/Denver",
               "JACK" = "America/New_York",
               "KANS" = "America/Chicago",
               "FTBL" = "America/Denver",
               "NAVL" = "America/New_York",
               "FTLV" = "America/Chicago",
               "FTJK" = "America/New_York",
               "BJCH" = "America/Chicago",
               "SSMH" = "America/Chicago",
               "TAMP" = "America/New_York",
               "PALM" = "America/New_York",
               "LAKE" = "America/New_York",
               "GREN" = "America/New_York",
               "DWTN" = "America/Chicago",
               "WEST" = "America/Chicago",
               "WING" = "America/Chicago",
               "FTLW" = "America/Chicago",
               "LAAB" = "America/Los_Angeles",
               "BOLL" = "America/New_York",
               "LUKE" = "America/Phoenix",
               "ONLN" = "America/Chicago",
               "LUTH" = "America/Chicago",
               "GENE" = "Europe/Zurich",
               "SOMA" = "America/New_York",
               "FTSL" = "America/Chicago",
               "TINK" = "America/Chicago",
               "VIEN" = "Europe/Vienna",
               "LEJE" = "America/New_York",
               "LEID" = "Europe/Amsterdam",
               "THAI" = "Asia/Bangkok",
               "BANG" = "Asia/Bangkok",
               "OCLA" = "America/New_York",
               "AMST" = "Europe/Amsterdam",
               "MEMP" = "America/Chicago",
               "RAND" = "America/Chicago",
               "ANDY" = "America/New_York",
               "LRAF" = "America/Chicago",
               "FTBG" = "America/New_York",
               "SATX" = "America/Chicago",
               "LOUI" = "America/Kentucky/Louisville",
               "FTST" = "America/New_York",
               "HNTR" = "America/New_York",
               "NEWR" = "America/New_York",
               "SHAW" = "America/New_York",
               "COLO" = "America/Denver",
               "HALL" = "America/New_York",
               "FTBV" = "America/New_York",
               "SANA" = "America/Denver",
               "CUYO" = "America/Argentina/Mendoza",
               "JFOU" = "Asia/Tokyo",
               "OXBR" = "Europe/London",
               "BLCU" = "Asia/Shanghai",
               "SCOT" = "America/Chicago",
               "LACK" = "America/Chicago",
               "IRVN" = "America/Los_Angeles",
               "MAFB" = "America/Chicago",
               "FTGO" = "America/New_York",
               "FAYE" = "America/New_York",
               "FTCH" = "America/Chicago",
               "RLLA" = "America/Chicago",
               "PETR" = "America/Denver",
               "MGHA" = "Africa/Accra",
               "GRTL" = "America/Chicago",
               "CHEN" = "Asia/Shanghai",
               "ATHE" = "Europe/Athens",
               "SCSW" = "America/Chicago",
               "SHNG" = "Asia/Shanghai",
               "CHAF" = "America/New_York",
               "BMED" = "America/New_York",
               "DENV" = "America/Denver",
               "ROSE" = "America/Denver",
               "MRCY" = "America/Chicago",
               "SCTD" = "America/Chicago",
               "UDOV" = "Europe/Madrid",
               "WGDL" = "America/Chicago",
               "FLNC" = "Europe/Rome",
               "UROE" = "Europe/London",
               "STAH" = "America/Chicago")
      
      if(!is.null(zones)) {
            TZs <- TZs[TZs %in% zones]
      }
      
      if(as.df == TRUE) {
            TZs <- data.frame("Location" = names(TZs), "TZ" = TZs, 
                              stringsAsFactors = FALSE)
      }
      
      return(TZs)
}